// Persistent local references; Node for Max. Audio never leaves this computer.
const fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto'),vm=require('vm'),{spawn}=require('child_process');
const core=vm.createContext({Math,JSON});vm.runInContext(fs.readFileSync(path.join(__dirname,'doppelganger_core.js'),'utf8'),core);
const platform=require('./doppelganger_platform.js');
const defaultRoot=platform.libraryRoot();
function validate(p){if(!p||typeof p.name!=='string'||!Array.isArray(p.power)||p.power.length!==61||!p.power.every(v=>Number.isFinite(v)&&v>0)||!Number.isFinite(p.rms))throw Error('Invalid reference analysis');return p;}
function characterize(p){validate(p);const totals=[0,0,0];for(let i=0;i<61;i++){const f=core.FREQ[i];totals[f<250?0:f<2000?1:2]+=p.power[i]*f;}const sum=totals.reduce((a,b)=>a+b,0),shares=totals.map(v=>v/sum),tags=[];if(shares[0]>=.55)tags.push('Bass-heavy');if(shares[2]>=.24)tags.push('Bright');if(shares[0]>=.38&&shares[2]<.12)tags.push('Warm');if(shares[1]>=.60)tags.push('Mid-forward');if(!tags.length)tags.push('Balanced');return {tags,shares};}
function read(root){const file=path.join(root,'library.json');if(!fs.existsSync(file))return {version:1,entries:[]};const db=JSON.parse(fs.readFileSync(file,'utf8'));if(db.version!==1||!Array.isArray(db.entries))throw Error('Library format is invalid; existing file was kept');for(const e of db.entries){validate(e.profile);if(!/^[a-f0-9]{64}$/.test(e.id))throw Error('Invalid library entry');}return db;}
function write(root,db){fs.mkdirSync(root,{recursive:true});const tmp=path.join(root,`library-${process.pid}-${crypto.randomBytes(4).toString('hex')}.tmp`);fs.writeFileSync(tmp,JSON.stringify(db,null,2));fs.renameSync(tmp,path.join(root,'library.json'));}
function hash(file){return new Promise((resolve,reject)=>{const h=crypto.createHash('sha256'),stream=fs.createReadStream(file);stream.on('error',reject);stream.on('data',d=>h.update(d));stream.on('end',()=>resolve(h.digest('hex')));});}
function executable(){return platform.findFFmpeg();}
function decode(file,out){return new Promise((resolve,reject)=>{const exe=executable();if(!exe)return reject(Error('Import requires local FFmpeg'));const child=spawn(exe,['-v','error','-nostdin','-y','-i',file,'-vn','-ar','44100','-ac','2','-f','f32le',out],{shell:false}),timer=setTimeout(()=>child.kill(),300000);let err='';child.stderr.on('data',d=>{err=(err+d).slice(-1000);});child.on('error',e=>{clearTimeout(timer);reject(e);});child.on('close',c=>{clearTimeout(timer);c===0?resolve():reject(Error('Could not decode this audio file. '+err.slice(0,160)));});});}
async function scan(file,onProgress){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'doppelganger-ref-'));try{const raw=path.join(dir,'audio.f32');await decode(file,raw);const count=Math.floor(fs.statSync(raw).size/8),n=32768;if(count<n)throw Error('Choose audio at least 0.75 seconds long');const fd=fs.openSync(raw,'r'),frames=[],bytes=Buffer.alloc(n*8);try{for(let i=0;i<128;i++){fs.readSync(fd,bytes,0,bytes.length,Math.floor((count-n)*i/127)*8);const left=new Float32Array(n),right=new Float32Array(n);let rms=0;for(let k=0;k<n;k++){left[k]=bytes.readFloatLE(k*8);right[k]=bytes.readFloatLE(k*8+4);rms+=(left[k]*left[k]+right[k]*right[k])/(2*n);}const power=core.fftPower(left),r=core.fftPower(right);for(let k=0;k<power.length;k++)power[k]=(power[k]+r[k])*.5;frames.push({bands:core.bands(power,44100,n),rms,stats:core.stereoStats(left,right)});if(i%8===0){if(onProgress)onProgress(i/128);await new Promise(resolve=>setImmediate(resolve));}}}finally{fs.closeSync(fd);}const p=JSON.parse(JSON.stringify(core.profile(frames,path.basename(file))));p.duration=count/44100;return validate(p);}finally{fs.rmSync(dir,{recursive:true,force:true});}}
function resolveAudioPath(file){return platform.resolveAudioPath(file);}
async function importTrack(file,root=defaultRoot,provided,onProgress){file=resolveAudioPath(file);if(typeof file!=='string'||!fs.statSync(file).isFile())throw Error('Choose an audio file');file=fs.realpathSync(file);const id=await hash(file);let db=read(root),existing=db.entries.find(e=>e.id===id);if(existing){existing.sourcePath=file;existing.profile.filePath=file;write(root,db);return existing;}const profile=provided?validate(JSON.parse(JSON.stringify(provided))):await scan(file,onProgress);profile.filePath=file;db=read(root);existing=db.entries.find(e=>e.id===id);if(existing){existing.sourcePath=file;existing.profile.filePath=file;write(root,db);return existing;}const entry={id,name:profile.name,profile,sourcePath:file,added:new Date().toISOString(),...characterize(profile)};db.entries.push(entry);write(root,db);return entry;}
function snapshot(root=defaultRoot,status='Ready'){return {status,entries:read(root).entries.map(e=>({id:e.id,name:e.name,sourcePath:e.sourcePath||null,...characterize(e.profile),duration:e.profile.duration||null}))};}
function attach(max){let busy=false,status='Ready',queue=[],progress={phase:'idle',name:'Library',progress:0};const publish=()=>{try{max.outlet('librarydata',JSON.stringify({...snapshot(defaultRoot,status),progress}));}catch(e){max.outlet('librarydata',JSON.stringify({entries:[],status:e.message,error:true}));}};
max.addHandler('librarylist',publish);
max.addHandler('librarychoose',()=>{if(busy){status='An import is already running';publish();return;}max.outlet('librarydialog','bang');});
async function importing(file,p){if(busy){queue.push([file,p]);status='Import queued ('+queue.length+' waiting)';publish();return;}busy=true;status='Importing '+path.basename(file)+'…';progress={phase:'loading',name:path.basename(file),progress:0};publish();try{const e=await importTrack(file,defaultRoot,p,value=>{progress={phase:'analyzing',name:path.basename(file),progress:value};publish();});progress={phase:'done',name:e.name,progress:1};status='Saved '+e.name;}catch(e){status='Import failed: '+e.message;progress={phase:'error',name:path.basename(file),message:e.message,progress:0};}finally{busy=false;publish();if(queue.length){const next=queue.shift();importing(next[0],next[1]);}}}
max.addHandler('libraryimport',(...parts)=>importing(parts.join(' ')));
max.addHandler('librarysave',(file,json)=>{try{return importing(file,JSON.parse(json));}catch(e){status='Save failed: '+e.message;publish();}});
max.addHandler('libraryget',(id,slot)=>{try{if(slot!==1&&slot!==2)return;const entry=read(defaultRoot).entries.find(e=>e.id===id);if(!entry)throw Error('Reference no longer available');max.outlet('libraryprofile',slot,JSON.stringify(entry.profile));status='Loaded '+entry.name+' into '+(slot===1?'A':'B');publish();}catch(e){status=e.message;publish();}});
publish();}
module.exports={validate,characterize,read,write,scan,importTrack,snapshot,attach,defaultRoot};
