// Offline paired-output measurements. Runs in Node for Max, never in the audio thread.
const fs=require('fs'),os=require('os'),path=require('path'),vm=require('vm'),{spawn}=require('child_process');
const platform=require('./doppelganger_platform.js');
const core=vm.createContext({Math,JSON});vm.runInContext(fs.readFileSync(path.join(__dirname,'doppelganger_core.js'),'utf8'),core);
function readWave(file){const b=fs.readFileSync(file);if(b.toString('ascii',0,4)!=='RIFF'||b.toString('ascii',8,12)!=='WAVE')throw Error('Capture is not WAV');let fmt,data;for(let p=12;p+8<=b.length;){const n=b.readUInt32LE(p+4),id=b.toString('ascii',p,p+4);if(p+8+n>b.length)throw Error('Incomplete capture');if(id==='fmt ')fmt=b.subarray(p+8,p+8+n);if(id==='data')data=b.subarray(p+8,p+8+n);p+=8+n+(n&1);}if(!fmt||!data)throw Error('Missing WAV chunks');let tag=fmt.readUInt16LE(0),channels=fmt.readUInt16LE(2),sr=fmt.readUInt32LE(4),bits=fmt.readUInt16LE(14);if(tag===65534&&fmt.length>=40)tag=fmt.readUInt16LE(24);if(channels!==4||tag!==3||bits!==32)throw Error('Measurement requires 4-channel float32 capture');const count=data.length/16,rows=Array.from({length:4},()=>new Float32Array(count));for(let i=0;i<count;i++)for(let c=0;c<4;c++){const v=data.readFloatLE(i*16+c*4);if(!Number.isFinite(v))throw Error('Non-finite audio sample');rows[c][i]=v;}return {rows,sr,count};}
function measurePair(w){const results=[];for(let pair=0;pair<2;pair++){let left=w.rows[pair*2],right=w.rows[pair*2+1],stats=core.stereoStats(left,right),rms=core.db((stats.ll+stats.rr)/(2*stats.count)),peak=20*Math.log10(Math.max(1e-20,stats.peak)),frames=[];const n=32768;for(let pos=0;pos+n<=w.count;pos+=n/2){let l=left.subarray(pos,pos+n),r=right.subarray(pos,pos+n),pl=core.fftPower(l),pr=core.fftPower(r),rmsFrame=0;for(let k=0;k<pl.length;k++)pl[k]=(pl[k]+pr[k])*.5;for(let k=0;k<n;k++)rmsFrame+=(l[k]*l[k]+r[k]*r[k])/(2*n);frames.push({bands:core.bands(pl,w.sr,n),rms:rmsFrame});}let prof=null;try{prof=core.profile(frames,pair?'Output':'Before');}catch(e){}results.push({power:prof?Array.from(prof.power):null,metrics:{rms,peak,crest:peak-rms,correlation:stats.ll*stats.rr>1e-24?Math.max(-1,Math.min(1,stats.lr/Math.sqrt(stats.ll*stats.rr))):null,sideMid:stats.mid>1e-24?Math.max(-100,core.db(stats.side/stats.mid)):null}});}return {before:results[0],after:results[1],seconds:w.count/w.sr,sr:w.sr};}
function ffmpegPath(){return platform.findFFmpeg();}
function loudness(file,pair){return new Promise((resolve,reject)=>{let exe=ffmpegPath();if(!exe)return reject(Error('FFmpeg unavailable: LUFS and true peak were not measured'));const c=pair*2,args=['-hide_banner','-nostats','-i',file,'-af',`pan=stereo|c0=c${c}|c1=c${c+1},loudnorm=I=-14:TP=-1:LRA=11:print_format=json`,'-f','null','-'];const child=spawn(exe,args,{shell:false}),timeout=setTimeout(()=>child.kill(),60000);let stderr='';child.stderr.on('data',d=>stderr+=d.toString());child.on('error',e=>{clearTimeout(timeout);reject(e);});child.on('close',code=>{clearTimeout(timeout);if(code)return reject(Error('Loudness scan failed'));try{const start=stderr.lastIndexOf('{'),end=stderr.indexOf('}',start),r=JSON.parse(stderr.slice(start,end+1)),number=v=>Number.isFinite(Number(v))?Number(v):null;resolve({lufs:number(r.input_i),truePeak:number(r.input_tp)});}catch(e){reject(Error('No loudness result'));}});});}
async function analyze(file){const w=readWave(file),result=measurePair(w),loud=await Promise.allSettled([loudness(file,0),loudness(file,1)]);for(let i=0;i<2;i++){let side=i?result.after:result.before;if(loud[i].status==='fulfilled')Object.assign(side.metrics,loud[i].value);else result.warning=String(loud[i].reason.message);}return result;}
module.exports={readWave,measurePair,analyze};
let max=null;try{max=require('max-api');}catch(e){}
if(max){require('./doppelganger_library.js').attach(max);let current=null,busy=false;
max.addHandler('prepare',async id=>{try{if(busy)throw Error('Analysis is busy');if(current)fs.rmSync(current.dir,{recursive:true,force:true});const dir=fs.mkdtempSync(path.join(os.tmpdir(),'doppelganger-'));current={id:String(id),dir,file:path.join(dir,'paired.wav')};max.outlet('measurepath',current.id,platform.toMaxPath(current.file));}catch(e){max.outlet('measureerror',String(id),e.message);}});
max.addHandler('analyze',async id=>{if(!current||String(id)!==current.id||busy)return;busy=true;const job=current;try{const result=await analyze(job.file);max.outlet('measureresult',job.id,JSON.stringify(result));}catch(e){max.outlet('measureerror',job.id,e.message);}finally{busy=false;fs.rmSync(job.dir,{recursive:true,force:true});if(current===job)current=null;}});
max.addHandler('discard',id=>{if(current&&!busy&&current.id===String(id)){fs.rmSync(current.dir,{recursive:true,force:true});current=null;}});
max.outlet('measureready');}
