autowatch=1;inlets=1;outlets=8;
include('doppelganger_core.js');include('doppelganger_defaults.js');
var profiles=JSON.parse(JSON.stringify(DEFAULT_PROFILES));
var cfg={mode:0,style:0,blend:50,amount:60,limit:4,output:0,drive:0,wet:100,bypass:0,start:0,end:100};
var referenceMix=[-1,-1,-1,-1,-1],dynamic={amount:0,range:3,threshold:-24,attack:25,release:180,punch:1,enabled:[1,1,1,1,1]};
var points=[],regions=[100,100,100,100,100],base=null,editPending=false,configPending=false;
var editTask=new Task(flushEdit,this);
var analysisState={phase:'idle',progress:0,name:'Choose source to analyze'},analysisQueue=[],sourceAutoLoaded=false;
var sourceRestoreTask=new Task(restoreSource,this);
var loadWatch=new Task(function(){if(analysisState.phase==='loading'){analysisState.phase='error';analysisState.message='Could not load audio. Choose a supported audio file.';analysispublish();}},this);
var pendingNames=['','',''],pendingPaths=['','',''];
var libraryState={entries:[],status:'Loading library…'};
function audiofilename(slot){var a=arrayfromargs(arguments);a.shift();var path=a.join(' ');pendingPaths[slot]=path;pendingNames[slot]=path.split('/').pop().split('\\').pop();}
var sr=44100,job=null,task=null,last=null,updateTask=new Task(update,this);
function notify(s){outlet(3,'set',s);}
include('doppelganger_live.js');
function getvalueof(){return JSON.stringify({version:3,sourceMode:sourceState.mode,sourceProfiles:sourceProfiles,profiles:profiles,points:points,regions:regions,referenceMix:referenceMix,dynamic:dynamic});}
function setvalueof(s){try{var saved=JSON.parse(s),p=saved.profiles;if(!p||p.length!==3)throw Error('Use doppelganger v0.2 profiles');for(var i=0;i<3;i++){if(p[i].power.length!==FREQ.length)throw Error('Reanalyze old profiles');for(var k=0;k<FREQ.length;k++)if(!(p[i].power[k]>0))throw Error('Invalid spectrum');}var next=saved.points||[];if(next.length>8)throw Error('Too many points');for(i=0;i<next.length;i++)if(!validPoint(next[i]))throw Error('Invalid EQ point');var weights=saved.regions||[100,100,100,100,100];if(weights.length!==5)throw Error("Invalid region controls");for(i=0;i<5;i++)if(!isFinite(weights[i])||weights[i]<0||weights[i]>100)throw Error("Invalid region amount");for(i=0;i<3;i++)if(!p[i].metrics&&JSON.stringify(p[i].power)===JSON.stringify(DEFAULT_PROFILES[i].power))p[i].metrics=DEFAULT_PROFILES[i].metrics;profiles=p;sourceState.mode=saved.sourceMode===0||saved.sourceMode===1?saved.sourceMode:2;sourceProfiles=saved.sourceProfiles||[null,null,null];sourceState.phase=p[0].empty?'idle':'held';points=next;regions=weights;referenceMix=[-1,-1,-1,-1,-1];if(saved.referenceMix&&saved.referenceMix.length===5)for(i=0;i<5;i++)referenceMix[i]=isFinite(saved.referenceMix[i])?clamp(saved.referenceMix[i],-1,100):-1;if(saved.dynamic){for(var dk in dynamic)if(dk!=="enabled"&&isFinite(saved.dynamic[dk]))dynamic[dk]=saved.dynamic[dk];if(saved.dynamic.enabled&&saved.dynamic.enabled.length===5)dynamic.enabled=saved.dynamic.enabled.map(function(v){return v?1:0;});}sanitizeDynamic();sourcepublish();update();sourceRestoreTask.schedule(700);}catch(e){notify(e.message);}}
function validPoint(p){return p&&isFinite(p.f)&&p.f>=32&&p.f<=16000&&isFinite(p.g)&&Math.abs(p.g)<=12&&isFinite(p.q)&&p.q>=.2&&p.q<=12;}
function editpoint(i,f,g,q){markCaptureChange();i=Math.floor(i);var p={f:clamp(Number(f),32,16000),g:clamp(Number(g),-12,12),q:clamp(Number(q),.2,12)};if(!validPoint(p)||i<0||i>points.length||i>=8)return;points[i]=p;if(!editPending){editPending=true;editTask.schedule(33);}}
function flushEdit(){editPending=false;publish(true);}
function commitpoints(){editTask.cancel();editPending=false;publish(true);notifyclients();}
function removepoint(i){markCaptureChange();if(i>=0&&i<points.length){points.splice(i,1);commitpoints();}}
function clearpoints(){markCaptureChange();points=[];commitpoints();}
function region(i,v){i=Math.floor(i);if(i<0||i>=5||!isFinite(v))return;regions[i]=clamp(Number(v),0,100);queueConfig();}
function queueConfig(){markCaptureChange();if(!configPending){configPending=true;updateTask.schedule(70);}}
function commitregions(){updateTask.cancel();update();notifyclients();}
function anything(){var a=arrayfromargs(arguments),key=messagename;if(cfg.hasOwnProperty(key)){var bounds={mode:[0,2],style:[0,3],blend:[0,100],amount:[0,100],limit:[0,9],output:[-18,6],drive:[0,9],wet:[0,100],bypass:[0,1],start:[0,99],end:[1,100]};cfg[key]=clamp(Number(a[0]),bounds[key][0],bounds[key][1]);if(key==='limit')cfg[key]=Math.round(cfg[key]*100)/100;queueConfig();}}
function samplerate(v){if(v>=22050){if(sr!==v&&measurement.phase==="capturing")measurecancel();sr=v;update();}}
function loadbang(){updateTask.schedule(150);sourceRestoreTask.schedule(700);}
function matchReady(){return !profiles[0].empty&&(!profiles[1].empty||!profiles[2].empty);}
function update(){configPending=false;if(!profiles||profiles.length!==3)return;var a=profiles[1].empty?profiles[2]:profiles[1],b=profiles[2].empty?profiles[1]:profiles[2];if(!matchReady())a=b=profiles[0];base=design(profiles[0],a,b,cfg.blend/100,(matchReady()?cfg.amount/100:0),cfg.limit,cfg.mode,cfg.style,sr,regions,referenceMix.map(function(v){return v<0?cfg.blend:v;}));publish();}
function publish(editOnly){if(!base)return;if(!editOnly)fileLabels();if(measurement.result)measurepublish();last=finishDesign(base,profiles[0],points,sr);sendDynamic();outlet(0,last.coefficients);outlet(1,Math.pow(10,((sourceState.mode===1?0:last.trim)+cfg.output+(cfg.mode===2?cfg.drive:0))/20));outlet(2,!matchReady()||cfg.mode===0||sourceBusy()?1:2);if(editOnly){outlet(4,'editdata',JSON.stringify({points:points,curve:last.curve,dense:last.dense,after:last.after,breakdown:breakdown(last)}));return;}outlet(4,'data',JSON.stringify({ready:matchReady(),sourceState:sourceState,analysis:analysisState,library:libraryState,measurement:measurement,cfg:cfg,result:{source:last.source,refA:last.refA,refB:last.refB,target:last.target,curve:last.curve,dense:last.dense,before:last.before,after:last.after,breakdown:breakdown(last)},regions:regions,referenceMix:referenceMix,dynamic:dynamic,metrics:profiles.map(function(p){return p.metrics||null;}),names:profiles.map(function(p){return p.name;}),points:points,sr:sr,buffers:[jsarguments[4],jsarguments[5]]}));var order=[];for(var i=0;i<FREQ.length;i++)order.push(i);order.sort(function(a,b){return Math.abs(last.target[b])-Math.abs(last.target[a]);});var tips=[];for(i=0;i<3;i++){var k=order[i];tips.push((last.target[k]<0?'Reduce ':'Lift ')+(FREQ[k]>=1000?(FREQ[k]/1000).toFixed(2)+'k':Math.round(FREQ[k]))+' Hz '+Math.abs(last.target[k]).toFixed(1)+' dB');}notify(!matchReady()?'Load source and a reference':cfg.bypass?'Bypassed':cfg.mode===0?'Advice · dry':(cfg.mode===1?'Filters':'Precision')+' · on');}
function analyze(slot){loadWatch.cancel();slot=Number(slot);if(slot<0||slot>2)return;if(job){if(job.slot===slot){task.cancel();job=null;}else{if(analysisQueue.indexOf(slot)<0)analysisQueue.push(slot);analysisState.queued=analysisQueue.length;analysispublish();return;}}var buf=new Buffer(jsarguments[slot+1]);var count=buf.framecount(),dur=buf.length(),rate=count/(dur/1000);if(count<FFT_SIZE||!(rate>0)){analysisState={phase:'error',progress:0,name:pendingNames[slot]||'Source',message:'Choose a longer audio file'};analysispublish();return;}job={slot:slot,buf:buf,sr:rate,start:0,end:count,index:0,frames:[],channels:Math.min(2,buf.channelcount())};analysisState={phase:'analyzing',slot:slot,name:pendingNames[slot]||profiles[slot].name,progress:0,queued:analysisQueue.length};analysispublish();task=new Task(step,this);task.interval=2;task.repeat();}
function step(){try{var n=FFT_SIZE,j=job;if(!j)return;var pos=Math.floor(j.start+(j.end-j.start-n)*j.index/127),p=[],rms=0,channels=[];for(var k=0;k<=n/2;k++)p[k]=0;for(var c=1;c<=j.channels;c++){var x=j.buf.peek(c,pos,n),sp=fftPower(x);channels.push(x);for(k=0;k<x.length;k++)rms+=x[k]*x[k]/(n*j.channels);for(k=0;k<p.length;k++)p[k]+=sp[k]/j.channels;}j.frames.push({bands:bands(p,j.sr,n),rms:rms,stats:stereoStats(channels[0],channels[1])});j.index++;if(j.index%4===0){analysisState.progress=j.index/128;analysispublish();}if(j.index>=128){task.cancel();profiles[j.slot]=profile(j.frames,pendingNames[j.slot]||profiles[j.slot].name);if(pendingPaths[j.slot])profiles[j.slot].filePath=pendingPaths[j.slot];if(j.slot>0&&pendingPaths[j.slot])outlet(6,'node','librarysave',pendingPaths[j.slot],JSON.stringify(profiles[j.slot]));job=null;analysisState={phase:'done',progress:1,name:profiles[j.slot].name,slot:j.slot};markCaptureChange();notifyclients();update();analysispublish();nextAnalysis();}}catch(e){if(task)task.cancel();job=null;analysisState={phase:'error',progress:0,name:analysisState.name,message:e.message};analysispublish();nextAnalysis();}}
function analysispublish(){outlet(4,'analysisdata',JSON.stringify(analysisState));}
function nextAnalysis(){if(analysisQueue.length)analyze(analysisQueue.shift());}
function cancel(){if(task)task.cancel();job=null;analysisQueue=[];analysisState={phase:'idle',progress:0,name:'Analysis cancelled'};analysispublish();}
function audioselected(slot){var a=arrayfromargs(arguments);a.shift();var path=a.join(' ').replace(/\\/g,'/');slot=Number(slot);if(slot<0||slot>2)return;if(!/\.(wav|aiff?|mp3|flac|m4a|ogg)$/i.test(path)){analysisState={phase:'error',progress:0,name:'Unsupported file',message:'Choose WAV, AIFF, MP3, FLAC, M4A or OGG audio.'};analysispublish();return;}if(slot===0&&sourceState.mode!==2)sourcemode(2);audiofilename(slot,path);if(job&&job.slot===slot){task.cancel();job=null;}if(!job){analysisState={phase:'loading',progress:0,slot:slot,name:pendingNames[slot]};analysispublish();}loadWatch.schedule(60000);try{if(this.patcher)this.patcher.getnamed('buf'+slot).message('replace',path);}catch(e){loadWatch.cancel();analysisState={phase:'error',progress:0,name:pendingNames[slot],message:e.message};analysispublish();}}
function restoreSource(){if(sourceState.mode!==2)return;if(sourceAutoLoaded||!profiles[0].filePath||!this.patcher)return;sourceAutoLoaded=true;try{audioselected(0,profiles[0].filePath);}catch(e){analysisState={phase:'error',name:profiles[0].name,message:'Source unavailable. Choose it again.',progress:0};analysispublish();}}
function resetprofiles(){learncancel();sourceProfiles=[null,null,null];cancel();profiles=JSON.parse(JSON.stringify(DEFAULT_PROFILES));points=[];notifyclients();update();}
function freebang(){learncancel();loadWatch.cancel();sourceRestoreTask.cancel();measureWatch.cancel();meterTask.cancel();editTask.cancel();if(task)task.cancel();updateTask.cancel();}
function bang(){if(!sourceAutoLoaded)sourceRestoreTask.schedule(700);if(base)publish();else update();}

function refmix(i,v){i=Math.floor(i);if(i<0||i>4||!isFinite(v))return;referenceMix[i]=clamp(v,-1,100);queueConfig();}
function sanitizeDynamic(){var bounds={amount:[0,100],range:[0,6],threshold:[-60,0],attack:[1,150],release:[30,1000],punch:[0,1]};for(var k in bounds)dynamic[k]=clamp(dynamic[k],bounds[k][0],bounds[k][1]);}
function dynparam(key,v){if(key==='enabled')return;if(dynamic.hasOwnProperty(key)&&isFinite(v)){markCaptureChange();dynamic[key]=Number(v);sanitizeDynamic();sendDynamic();if(measurement.result)measurepublish();outlet(4,'dynamicdata',JSON.stringify(dynamic));}}
function dynband(i){i=Math.floor(i);if(i>=0&&i<5){markCaptureChange();dynamic.enabled[i]=1-dynamic.enabled[i];sendDynamic();if(measurement.result)measurepublish();outlet(4,'dynamicdata',JSON.stringify(dynamic));notifyclients();}}
function commitdynamic(){notifyclients();}
function sendDynamic(){outlet(5,'amount',cfg.mode===0?0:dynamic.amount/100);outlet(5,'range',dynamic.range);outlet(5,'threshold',dynamic.threshold);outlet(5,'attack',dynamic.punch?Math.max(25,dynamic.attack):dynamic.attack);outlet(5,'release',dynamic.release);for(var i=0;i<5;i++)outlet(5,'enable'+i,dynamic.enabled[i]);}
var latestMeter=[0,0,0,0,0],meterPending=false,meterTask=new Task(function(){meterPending=false;outlet(4,'dynmeter',latestMeter);},this);
function dynmeter(){latestMeter=arrayfromargs(arguments);if(!meterPending){meterPending=true;meterTask.schedule(40);}}

var measurement={phase:'idle',progress:0,result:null,stale:false},measureId=0,measureFile='',measureReference=null,measureSignature='',nodeReady=false,measureLastProgress=0,measureLastTime=0;
var measureWatch=new Task(function(){if(measurement.phase==='capturing'&&new Date().getTime()-measureLastTime>5000){measurecancel();measurement.phase='error';measurement.error='Audio engine is not advancing. Enable audio and try again.';measurepublish();}},this);measureWatch.interval=1000;
function settingsSignature(){return JSON.stringify({cfg:cfg,points:points,regions:regions,referenceMix:referenceMix,dynamic:dynamic,profiles:profiles.map(function(p){return p.power;})});}
function measurepublish(){measurement.stale=!!measurement.result&&(!!measurement.changedDuringCapture||measureSignature!==settingsSignature());outlet(4,'measurementdata',JSON.stringify(measurement));}
function measureready(){nodeReady=true;outlet(6,'node','librarylist');}
function measurestart(){if(['preparing','capturing','writing','analyzing'].indexOf(measurement.phase)>=0)return;if(!nodeReady){measurement.phase='error';measurement.error='Measurement service is starting; try again shortly.';measurepublish();return;}measureId++;measurement={phase:'preparing',progress:0,result:null,stale:false};measureSignature=settingsSignature();measureReference=last.reference.slice();outlet(6,'node','prepare',String(measureId));measurepublish();}
function measurepath(id,path){if(String(id)!==String(measureId)||measurement.phase!=='preparing')return;measureFile=path;var cb=new Buffer(String(jsarguments[1]).replace(/-source$/,'-measure'));if(cb.framecount()<sr){measurement.phase='error';measurement.error='Capture buffer unavailable: '+cb.framecount()+' frames / '+cb.channelcount()+' channels';measurepublish();return;}outlet(6,'record','reset');measurement.phase='capturing';measureLastTime=new Date().getTime();measureLastProgress=0;outlet(6,'record',1);measureWatch.repeat();measurepublish();}
function measureprogress(v){if(measurement.phase!=='capturing')return;if(v>measureLastProgress){measureLastProgress=v;measureLastTime=new Date().getTime();measurement.progress=v;measurepublish();}}
function measurecomplete(){if(measurement.phase!=='capturing')return;measureWatch.cancel();measurement.phase='writing';measurement.progress=1;measurepublish();outlet(6,'buffer','writewave',measureFile);}
function measurewritten(){if(measurement.phase!=='writing')return;measurement.phase='analyzing';measurepublish();outlet(6,'node','analyze',String(measureId));}
function measureresult(id,s){if(String(id)!==String(measureId)||measurement.phase!=='analyzing')return;try{var r=JSON.parse(s);for(var i=0;i<2;i++){var side=i?r.after:r.before;side.score=side.power?tonalScore(normalized(side.power),measureReference,null,r.sr):null;}r.capturedMode=JSON.parse(measureSignature).cfg.mode;measurement.result=r;measurement.phase='done';measurement.error=null;measurepublish();}catch(e){measureerror(id,e.message);}}
function measureerror(id){if(String(id)!==String(measureId))return;var a=arrayfromargs(arguments);a.shift();measurement.phase='error';measurement.error=a.join(' ');measureWatch.cancel();measurepublish();}
function measurecancel(){var old=measureId;measurement.phase='idle';measureId++;measureWatch.cancel();outlet(6,'record',0);outlet(6,'node','discard',String(old));measurepublish();}

function markCaptureChange(){if(measurement&&['preparing','capturing','writing','analyzing'].indexOf(measurement.phase)>=0)measurement.changedDuringCapture=true;}

// The library is shared across devices on this computer. Live Sets also retain loaded profiles.
function librarydata(s){try{libraryState=JSON.parse(s);outlet(4,'librarydata',s);}catch(e){notify('Library: '+e.message);}}
function libraryopen(){outlet(6,'node','librarylist');}
function libraryimport(){outlet(6,'node','librarychoose');}
function libraryload(id,slot){if(slot!==1&&slot!==2)return;outlet(6,'node','libraryget',id,slot);}
function libraryprofile(slot,s){if(slot!==1&&slot!==2)return;try{var p=JSON.parse(s);if(!p.power||p.power.length!==61||!p.power.every(function(v){return isFinite(v)&&v>0;}))throw Error('Invalid saved profile');markCaptureChange();profiles[slot]=p;notifyclients();update();}catch(e){notify('Library: '+e.message);}}

// Keep native click/drop controls labeled from the active profiles, including library loads and restored Sets.
function fileLabels(){if(!this.patcher)return;for(var i=0;i<3;i++){try{var name=profiles[i].name||'Choose audio',shortName=name.replace(/\.(wav|aiff?|mp3|flac|m4a|ogg)$/i,''),label=['S · ','A · ','B · '][i]+shortName;if(profiles[i].empty)label=['Source','Ref A','Ref B'][i]+' · click / drop';if(i===0&&sourceState.mode!==2)label=sourceBusy()?'Hold':'Learn';if(label.length>24)label=label.slice(0,21)+'…';var control=this.patcher.getnamed('load'+i);control.message('text',label);control.message('texton',label);control.message('hint',['Source','Reference A','Reference B'][i]+': '+name+' — Click to choose audio, or drop a file here.');control.message('annotation',['Source','Reference A','Reference B'][i]+': '+name);control.message('fontsize',9);}catch(e){}}}
