/* Included by the engine: saved live-source state, finite Learn/Hold, message-only master feed. */
var sourceState={mode:0,phase:'idle',message:'Play audio, then Learn',progress:0},sourceProfiles=[null,null,null],learnTicket='',learnOwner='',learnSerial=0;
var learnTimeout=new Task(function(){if(learnTicket)learnFail('Master Feed not responding. Add one Master Feed device at the end of the master chain.');},this);
function sourceBusy(){return sourceState.phase==='capturing'||sourceState.phase==='analyzing'||sourceState.phase==='waiting';}
function sourceSend(command){if(sourceState.mode===1)outlet(7,'master',command,learnTicket);else outlet(7,'local',command,learnTicket);}
function sourcepublish(){try{this.patcher.getnamed('source_mode').message('set',sourceState.mode);}catch(ignore){}outlet(4,'sourcedata',JSON.stringify(sourceState));fileLabels();}
function sourcemode(v){v=Math.floor(Number(v));if(v<0||v>2||v===sourceState.mode)return;learncancel();if(job&&job.slot===0){task.cancel();job=null;}analysisQueue=analysisQueue.filter(function(i){return i!==0;});sourceProfiles[sourceState.mode]=profiles[0];sourceState.mode=v;profiles[0]=sourceProfiles[v]||JSON.parse(JSON.stringify(DEFAULT_PROFILES[0]));sourceState.phase=profiles[0].empty?'idle':'held';sourceState.message=v===1?'Enable allowed regions in Analysis; then Learn':v===0?'Play audio, then Learn':'Choose a source file';if(v===1){regions=[0,0,0,0,0];points=[];dynamic.amount=0;}sourceAutoLoaded=false;notifyclients();update();sourcepublish();}
function sourceaction(){if(sourceState.mode===2){try{this.patcher.getnamed('read0').message('bang');}catch(e){}return;}if(sourceBusy())learnhold();else learnstart();}
function learnstart(){if(sourceState.mode===2||sourceBusy())return;if(measurement&&['preparing','capturing','writing','analyzing'].indexOf(measurement.phase)>=0){sourceState.message='Finish output measurement first';sourcepublish();return;}if(job){sourceState.message='Wait for file analysis to finish';sourcepublish();return;}learnTicket=String(jsarguments[1])+'-'+(++learnSerial)+'-'+new Date().getTime();learnOwner='';sourceState.phase='waiting';sourceState.progress=0;sourceState.message='Waiting for audio';analysisState={phase:'capturing',name:'Learning source',progress:0};learnTimeout.schedule(6000);sourceSend('request');update();sourcepublish();analysispublish();}
function learnhold(){if(sourceBusy())sourceSend('hold');}
function learncancel(){if(learnTicket)sourceSend('abort');learnTicket='';learnTimeout.cancel();if(sourceBusy()){sourceState.phase=profiles[0].empty?'idle':'held';analysisState={phase:'idle',progress:0,name:'Learning cancelled'};analysispublish();}update();sourcepublish();}
function learnFail(message){learncancel();sourceState.phase='error';sourceState.message=message;analysisState={phase:'error',progress:0,message:message};update();analysispublish();sourcepublish();}
function learnevent(s){var e;try{e=JSON.parse(s);}catch(ignore){return;}if(!learnTicket||e.id!==learnTicket)return;if(learnOwner&&learnOwner!==e.owner){learnFail('More than one Master Feed responds. Keep only one active feed.');return;}learnOwner=e.owner;learnTimeout.cancel();if(e.kind==='error'){learnFail(e.value);return;}if(e.kind==='started'||e.kind==='progress'||e.kind==='analyzing'){sourceState.phase=e.kind==='analyzing'?'analyzing':'capturing';sourceState.progress=Number(e.value)||0;sourceState.message=e.kind==='analyzing'?'Analyzing captured audio':'Learning · Hold after 3s, automatic at 20s';analysisState={phase:sourceState.phase,progress:sourceState.progress,name:sourceState.mode===1?'Master feed':'Live input'};learnTimeout.schedule(7000);sourcepublish();analysispublish();return;}if(e.kind==='result'){var p=e.value;if(!p||!p.power||p.power.length!==61||!p.power.every(function(v){return isFinite(v)&&v>0;})){learnFail('Invalid learned spectrum');return;}p.name=sourceState.mode===1?'Master feed · held':'Live input · held';p.sourceMode=sourceState.mode;profiles[0]=p;sourceProfiles[sourceState.mode]=p;learnTicket='';sourceState.phase='held';sourceState.progress=1;sourceState.message=sourceState.mode===1?'Held · master-guided EQ; measure the master to verify':'Held · Learn again when the passage changes';analysisState={phase:'done',progress:1,name:p.name};markCaptureChange();notifyclients();update();sourcepublish();analysispublish();}}
