const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=__dirname;
function Task(fn,ctx){this.fn=()=>fn.call(ctx);this.schedule=this.cancel=this.repeat=function(){};}
const noop=()=>{},draw=new Proxy({init:noop},{get:(o,k)=>o[k]||noop,set:(o,k,v)=>(o[k]=v,true)});let engine,graph,notified=0;
engine=vm.createContext({Task,console,Math,JSON,isFinite,jsarguments:["engine","source","a","b","left","right"],arrayfromargs:a=>Array.from(a),notifyclients:()=>notified++,outlet:(port,name,...args)=>{if(port===4&&graph)graph[name](...args);}});engine.include=n=>vm.runInContext(fs.readFileSync(path+'/'+n,'utf8'),engine);
vm.runInContext(fs.readFileSync(path+'/doppelganger_engine.js','utf8'),engine);
graph=vm.createContext({Task,Buffer:function(){this.peek=()=>Array(4096).fill(0);},mgraphics:draw,box:{rect:[0,0,1040,560]},outlet:(port,name,...args)=>{if(name==='amount'){engine.messagename='amount';engine.anything(...args);}else engine[name](...args);}});graph.include=n=>vm.runInContext(fs.readFileSync(path+'/'+n,'utf8'),graph);vm.runInContext(fs.readFileSync(path+'/doppelganger_graph.js','utf8'),graph);
// Explicit audio fixtures: the shipping defaults are intentionally empty.
engine.profiles=JSON.parse(fs.readFileSync(path+'/test_profiles.json','utf8'));engine.update();graph.view=0;const original=Array.from(engine.last.dense),z=graph.size();
function xy(f){return [graph.fx(f,z),graph.gy(graph.curveAt(f),z)];}
function click(x,y){graph.onclick(x,y,1,0,0,0,0);graph.ondrag(x,y,0);}
let [x,y]=xy(1000);click(x,y);assert.equal(engine.points.length,1);assert.equal(engine.points[0].g,0);assert.deepEqual(Array.from(engine.last.dense),original,'Adding a point must be sonically neutral');
const saved=engine.getvalueof();let n=notified;graph.onclick(x+2,y+1,1,0,0,0,0);graph.ondrag(x+2,y+1,1);assert.equal(engine.points[0].g,0,'Mouse down must not shift gain');assert.equal(notified,n,'No state write during a grab');const beforeDrag=Array.from(graph.state.result.dense);graph.ondrag(x+40,y-25,1);assert(engine.points[0].g>0);assert.notDeepEqual(Array.from(graph.state.result.dense),beforeDrag,'Curve must redraw before any engine response');const immediate=Array.from(graph.state.result.dense);graph.editdata(JSON.stringify({points:[{f:1000,g:0,q:1.4}],curve:original.slice(0,61),dense:original,after:{percent:0}}));assert.deepEqual(Array.from(graph.state.result.dense),immediate,'Stale replies cannot roll back the drag');assert.equal(notified,n,'No state write for drag events');engine.flushEdit();graph.ondrag(x+40,y-25,0);assert.equal(notified,n+1,'Commit once on release');
[x,y]=xy(engine.points[0].f);click(x,y);assert.equal(engine.points.length,0);assert.deepEqual(Array.from(engine.last.dense),original,'Removing a changed point restores the automatic curve exactly');
engine.setvalueof(saved);assert.equal(engine.points.length,1);[x,y]=xy(engine.points[0].f);graph.onclick(x,y,1,0,0,0,0);graph.ondrag(x+1,y+1,0);assert.equal(engine.points.length,0,'Click jitter must delete, not change gain');
// Preserve other edits when deleting one band.
engine.editpoint(0,500,3,1.4);engine.commitpoints();const one=Array.from(engine.last.dense);engine.editpoint(1,2000,-2,2);engine.commitpoints();[x,y]=xy(2000);click(x,y);assert.equal(engine.points.length,1);assert.deepEqual(Array.from(engine.last.dense),one,'Deletion only removes its own correction');
graph.selected=0;const q=engine.points[0].q;graph.onclick(660,540,1);assert(engine.points[0].q<q,'Wider lowers Q');graph.onclick(760,540,1);assert(Math.abs(engine.points[0].q-q)<1e-10,'Narrower raises Q');
engine.clearpoints();for(let i=0;i<9;i++){[x,y]=xy(40*Math.pow(300,i/8));click(x,y);}assert.equal(engine.points.length,8);
graph.onclick(900,75);assert.equal(graph.view,1);graph.paint();assert.equal(graph.tabs.length,7);assert.equal(graph.tabs[6][0],'Spectrum / Image');graph.onclick(190,75);assert.equal(graph.view,0);graph.paint();
console.log('Passed: neutral single-click add; no jump on grab; drag threshold; throttled edits; commit on release; single-click deletion; exact restoration; other points preserved; Q buttons; point limit; all views.');

graph.pollSpectrum();graph.paint();assert.equal(graph.liveCurves[0].length,512);assert(graph.liveCurves[0].every(v=>v===-100));console.log("Live spectrum: silence floor and rendering pass.");
const fftPowerLeft=Array(4096).fill(0),fftPowerRight=Array(4096).fill(0);fftPowerLeft[186]=8192*8192/16*.25;fftPowerRight[650]=8192*8192/16*.25;graph.liveBuffers=[{peek:()=>fftPowerLeft},{peek:()=>fftPowerRight}];graph.liveCurves=[[],[]];graph.pollSpectrum();for(let ch=0;ch<2;ch++){let values=Array.from(graph.liveCurves[ch]),i=values.indexOf(Math.max(...values)),shown=32*Math.pow(500,i/511),actual=(ch===0?186:650)*44100/8192;assert(Math.abs(Math.log(shown/actual))<.02,'Live peak aligns with known FFT frequency on the EQ axis');}console.log('Live spectrum: independent stereo peaks align to the common frequency axis.');
engine.clearpoints();engine.regions=[0,0,0,0,0];engine.update();assert(engine.last.dense.every(v=>Math.abs(v)<1e-8),'Zero regional amounts disable automatic EQ');engine.regions=[100,100,100,100,100];engine.update();const expectedBefore=engine.last.before.percent;const regionalSave=engine.getvalueof();engine.region(2,23);engine.commitregions();assert.equal(JSON.parse(engine.getvalueof()).regions[2],23);engine.setvalueof(regionalSave);assert.equal(engine.regions[2],100);assert.equal(engine.last.before.percent,expectedBefore);graph.onclick(350,75);assert.equal(graph.view,3);graph.paint();graph.onclick(680,215,1);graph.ondrag(640,215,0);assert.equal(engine.regions[0],25);assert.equal(graph.state.result.breakdown.length,5);console.log('Analysis: regional zero/baseline, persistence, draggable regional amounts and all five explanations pass.');

graph.onclick(500,128,1);graph.ondrag(500,128,0);assert.equal(engine.cfg.amount,50);assert.equal(graph.state.cfg.amount,50);console.log("Global Match Amount bar updates the existing amount parameter path.");
// New controls route correctly, stay bounded and survive device state reload.
graph.arrayfromargs=a=>Array.from(a);
graph.outlet=(port,name,...args)=>{if(['amount','output','drive'].includes(name)){engine.messagename=name;engine.anything(...args);}else engine[name](...args);};
graph.onclick(650,75);assert.equal(graph.view,5);graph.paint();graph.onclick(500,128,1);graph.ondrag(760,128,0);assert.equal(engine.dynamic.amount,100);engine.dynparam('range',99);assert.equal(engine.dynamic.range,6);engine.dynparam('range',3);engine.dynband(2);assert.equal(engine.dynamic.enabled[2],0);graph.dynmeter(-1,-2,0,-.5,-.2);graph.paint();
graph.onclick(350,75);graph.onclick(40,230,1);assert.equal(engine.referenceMix[0],0);graph.onclick(130,287,1);assert.equal(engine.referenceMix[1],100);const mixsave=engine.getvalueof();engine.refmix(0,100);engine.setvalueof(mixsave);assert.equal(engine.referenceMix[0],0);assert.equal(engine.dynamic.amount,100);assert.equal(engine.dynamic.enabled[2],0);
graph.onclick(500,75);graph.paint();graph.onclick(122,499,1);graph.ondrag(122,499,0);assert.equal(engine.cfg.output,-6);graph.onclick(622,499,1);graph.ondrag(622,499,0);assert.equal(engine.dynamic.amount,50);graph.onclick(190,75);graph.paint();console.log('Dynamic controls: bounds, enable switches, meters, state restore, per-region reference choice and Whole Mix sliders pass.');
engine.Buffer=function(){this.framecount=()=>441000;this.length=()=>10000;this.channelcount=()=>2;};engine.cfg.start=40;engine.cfg.end=60;for(let slot=0;slot<3;slot++){engine.analyze(slot);assert.equal(engine.job.start,0);assert.equal(engine.job.end,441000);engine.cancel();}console.log('Full-file analysis: all three slots ignore legacy range values.');
engine.measureready();engine.measurestart();let mid=engine.measureId;assert.equal(engine.measurement.phase,'preparing');engine.measurepath(mid,'/tmp/test.wav');assert.equal(engine.measurement.phase,'capturing');engine.measureprogress(.5);assert.equal(engine.measurement.progress,.5);engine.measurecomplete();assert.equal(engine.measurement.phase,'writing');engine.measurewritten();assert.equal(engine.measurement.phase,'analyzing');let fake={before:{power:engine.profiles[0].power,metrics:{rms:-12}},after:{power:engine.profiles[0].power,metrics:{rms:-12}},seconds:30,sr:44100};engine.measureresult(mid,JSON.stringify(fake));assert.equal(engine.measurement.phase,'done');assert.equal(engine.measurement.result.before.score.percent,engine.measurement.result.after.score.percent);assert(!engine.measurement.stale);engine.dynparam('amount',60);assert(engine.measurement.stale);graph.view=4;graph.mixView=1;graph.paint();engine.measurestart();mid=engine.measureId;engine.measurepath(mid,'/tmp/test.wav');engine.dynparam('amount',40);engine.dynparam('amount',60);engine.measurecomplete();engine.measurewritten();engine.measureresult(mid,JSON.stringify(fake));assert(engine.measurement.stale,'Changing and restoring settings during capture still invalidates a fixed-settings comparison');engine.measurestart();mid=engine.measureId;engine.measurecancel();engine.measureresult(mid,JSON.stringify(fake));assert.equal(engine.measurement.phase,'idle');console.log('Measurement lifecycle: phases, same-signal score, stale results, mixed-settings capture, canceled-response rejection and UI paint pass.');
// Library UI filtering, paging, A/B routing and saved-profile validation.
let libraryCall=null;const priorOutlet=graph.outlet;graph.outlet=(port,name,...args)=>{if(name==='libraryload')libraryCall=args;else priorOutlet(port,name,...args);};
engine.librarydata(JSON.stringify({status:'Ready',entries:[{id:'a',name:'Bass reference',tags:['Bass-heavy'],shares:[.8,.1,.1]},{id:'b',name:'Bright reference',tags:['Bright'],shares:[.2,.2,.6]}]}));
graph.onclick(790,75);assert.equal(graph.view,6);graph.paint();graph.onclick(320,160);assert.equal(graph.libraryEntries().length,1);graph.onclick(880,235);assert.deepEqual(libraryCall,['b',1]);graph.onclick(970,235);assert.deepEqual(libraryCall,['b',2]);graph.onclick(55,160);assert.equal(graph.libraryEntries().length,2);graph.paint();
const oldA=JSON.stringify(engine.profiles[1]);engine.libraryprofile(1,JSON.stringify({name:'bad',power:[0]}));assert.equal(JSON.stringify(engine.profiles[1]),oldA);engine.libraryprofile(1,JSON.stringify(engine.profiles[2]));assert.equal(engine.profiles[1].name,engine.profiles[2].name);
engine.messagename='wet';engine.anything(-5);assert.equal(engine.cfg.wet,0);engine.anything(105);assert.equal(engine.cfg.wet,100);console.log('PASS: library view, tonal filter, A/B selection, invalid-profile rejection and Dry/Wet bounds.');
const labelMessages={};engine.patcher={getnamed:id=>({message:(key,value)=>{(labelMessages[id]||(labelMessages[id]={}))[key]=value;}})};
engine.sourceState.mode=2;engine.audiofilename(0,'/audio/My Source Track.wav');assert.equal(engine.pendingNames[0],'My Source Track.wav');
engine.profiles[0].name=engine.pendingNames[0];engine.update();assert.equal(labelMessages.load0.text,'S · My Source Track');assert(labelMessages.load0.hint.includes('My Source Track.wav'));
const namedSave=engine.getvalueof();engine.profiles[0].name='wrong';engine.setvalueof(namedSave);assert.equal(labelMessages.load0.text,'S · My Source Track');assert(labelMessages.load1.text.startsWith('A · '));assert(labelMessages.load2.text.startsWith('B · '));console.log('PASS: selected source filename label, full filename hint and saved-name restoration.');
const bypassOutlet=graph.outlet;graph.outlet=(port,name,...args)=>{if(name==='bypass'){engine.messagename=name;engine.anything(...args);engine.update();}else bypassOutlet(port,name,...args);};
engine.cfg.wet=63;engine.cfg.bypass=0;engine.update();const beforeBypass=JSON.stringify({points:engine.points,dynamic:engine.dynamic,mode:engine.cfg.mode,amount:engine.cfg.amount});graph.onclick(630,29);assert.equal(engine.cfg.bypass,1);assert.equal(graph.state.cfg.bypass,1);assert.equal(engine.cfg.wet,63);graph.paint();graph.onclick(630,29);assert.equal(engine.cfg.bypass,0);assert.equal(JSON.stringify({points:engine.points,dynamic:engine.dynamic,mode:engine.cfg.mode,amount:engine.cfg.amount}),beforeBypass);console.log('PASS: editor bypass toggles shared state without changing processing settings or Dry/Wet.');
// Correction shading follows lightweight knob messages before the fitter responds.
graph.correctionShown=4;graph.correctionlimit(7.23);assert.equal(graph.correctionTarget,7.23);graph.animateCorrection();assert(graph.correctionShown>4&&graph.correctionShown<7.23);for(let i=0;i<20;i++)graph.animateCorrection();assert.equal(graph.correctionShown,7.23);assert.equal(graph.correctionAnimating,false);graph.correctionlimit(0);for(let i=0;i<20;i++)graph.animateCorrection();assert.equal(graph.correctionShown,0);assert.equal(graph.correctionAnimating,false);console.log('PASS: correction shading interpolates, settles exactly, and stops its animation task.');
